package db.migration;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V13__surrogate_primary_keys extends BaseJavaMigration {

    private static final List<String> STRING_ID_TABLES = Arrays.asList(
            "digital_team_project",
            "digital_team_project_conversation",
            "digital_team_project_message",
            "digital_team_project_event",
            "digital_team_coordinator_dispatch",
            "digital_team_coordinator_analysis",
            "digital_team_coordinator_human_request",
            "digital_team_coordinator_plan",
            "digital_team_coordinator_task",
            "digital_team_human_request",
            "digital_team_project_artifact",
            "digital_team_coordinator_agent_run",
            "digital_team_prompt_template",
            "digital_team_prompt_execution");

    private static final List<String> TECHNICAL_ID_TABLES = Arrays.asList(
            "digital_team_schema_version_marker",
            "digital_team_permission_audit_log",
            "digital_team_coordinator_task_event");

    private static final List<String> ASSOCIATION_TABLES = Arrays.asList(
            "digital_team_project_member",
            "digital_team_project_expert",
            "digital_team_project_event_sequence",
            "digital_team_conversation_event_sequence",
            "digital_team_project_artifact_lineage");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        boolean mysql = "MySQL".equalsIgnoreCase(
                connection.getMetaData().getDatabaseProductName());
        List<ForeignKey> foreignKeys = importedKeys(connection);
        try (Statement statement = connection.createStatement()) {
            statement.execute(mysql
                    ? "ALTER TABLE digital_team_project_message DROP INDEX uk_message_idempotency"
                    : "ALTER TABLE digital_team_project_message DROP CONSTRAINT uk_message_idempotency");
            statement.execute(
                    "ALTER TABLE digital_team_project_message DROP COLUMN idempotency_key");
            for (ForeignKey foreignKey : foreignKeys) {
                statement.execute("ALTER TABLE " + foreignKey.table
                        + (mysql ? " DROP FOREIGN KEY " : " DROP CONSTRAINT ")
                        + identifier(foreignKey.name, mysql));
            }
            for (String table : STRING_ID_TABLES) {
                migrateStringIdTable(connection, statement, table, mysql);
            }
            for (String table : ASSOCIATION_TABLES) {
                migrateAssociationTable(connection, statement, table, mysql);
            }
            for (String table : TECHNICAL_ID_TABLES) {
                addBusinessId(statement, table, mysql);
            }
            for (ForeignKey foreignKey : foreignKeys) {
                statement.execute(foreignKey.createSql());
            }
        }
    }

    private void migrateStringIdTable(
            Connection connection, Statement statement, String table, boolean mysql)
            throws Exception {
        if (mysql) {
            statement.execute("ALTER TABLE " + table
                    + " CHANGE COLUMN id business_id VARCHAR(64) NOT NULL");
            statement.execute("ALTER TABLE " + table
                    + " DROP PRIMARY KEY, ADD COLUMN id BIGINT NOT NULL "
                    + "AUTO_INCREMENT PRIMARY KEY FIRST");
        } else {
            dropPrimaryKey(connection, statement, table, false);
            statement.execute("ALTER TABLE " + table + " RENAME COLUMN id TO business_id");
            statement.execute("ALTER TABLE " + table
                    + " ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        }
        statement.execute("ALTER TABLE " + table + " ADD CONSTRAINT uk_"
                + abbreviate(table) + "_business_id UNIQUE (business_id)");
    }

    private void migrateAssociationTable(
            Connection connection, Statement statement, String table, boolean mysql)
            throws Exception {
        List<String> primaryKey = primaryKey(connection, table);
        if (!primaryKey.isEmpty()) {
            dropPrimaryKey(connection, statement, table, mysql);
        }
        statement.execute("ALTER TABLE " + table + " ADD COLUMN id BIGINT "
                + (mysql
                        ? "NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST"
                        : "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"));
        if (!primaryKey.isEmpty()) {
            statement.execute("ALTER TABLE " + table + " ADD CONSTRAINT uk_"
                    + abbreviate(table) + "_business UNIQUE ("
                    + String.join(", ", primaryKey) + ")");
        }
    }

    private void addBusinessId(
            Statement statement, String table, boolean mysql) throws Exception {
        statement.execute("ALTER TABLE " + table
                + " ADD COLUMN business_id VARCHAR(96)");
        statement.execute("UPDATE " + table + " SET business_id = CONCAT('"
                + table + "-', id)");
        statement.execute("ALTER TABLE " + table + (mysql
                ? " MODIFY COLUMN business_id VARCHAR(96) NOT NULL"
                : " ALTER COLUMN business_id VARCHAR(96) NOT NULL"));
        statement.execute("ALTER TABLE " + table + " ADD CONSTRAINT uk_"
                + abbreviate(table) + "_business_id UNIQUE (business_id)");
    }

    private List<String> primaryKey(Connection connection, String table) throws Exception {
        Map<Short, String> columns = new LinkedHashMap<>();
        DatabaseMetaData metadata = connection.getMetaData();
        String metadataTable = metadataTable(connection, table);
        try (ResultSet rows = metadata.getPrimaryKeys(
                connection.getCatalog(), connection.getSchema(), metadataTable)) {
            while (rows.next()) {
                columns.put(rows.getShort("KEY_SEQ"), rows.getString("COLUMN_NAME"));
            }
        }
        return new ArrayList<>(columns.values());
    }

    private void dropPrimaryKey(
            Connection connection, Statement statement, String table, boolean mysql)
            throws Exception {
        if (mysql) {
            statement.execute("ALTER TABLE " + table + " DROP PRIMARY KEY");
            return;
        }
        String name = null;
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet rows = metadata.getPrimaryKeys(
                connection.getCatalog(), connection.getSchema(),
                metadataTable(connection, table))) {
            if (rows.next()) {
                name = rows.getString("PK_NAME");
            }
        }
        if (name == null) {
            throw new IllegalStateException("Primary key was not found for " + table);
        }
        statement.execute("ALTER TABLE " + table + " DROP CONSTRAINT "
                + identifier(name, false));
    }

    private List<ForeignKey> importedKeys(Connection connection) throws Exception {
        List<ForeignKey> result = new ArrayList<>();
        DatabaseMetaData metadata = connection.getMetaData();
        for (String table : allTables()) {
            Map<String, ForeignKey> byName = new LinkedHashMap<>();
            try (ResultSet rows = metadata.getImportedKeys(
                    connection.getCatalog(), connection.getSchema(),
                    metadataTable(connection, table))) {
                while (rows.next()) {
                    String name = rows.getString("FK_NAME");
                    ForeignKey key = byName.computeIfAbsent(
                            name,
                            ignored -> new ForeignKey(
                                    name,
                                    rowsValue(rows, "FKTABLE_NAME"),
                                    rowsValue(rows, "PKTABLE_NAME")));
                    key.fkColumns.add(rows.getString("FKCOLUMN_NAME"));
                    String referenced = rows.getString("PKCOLUMN_NAME");
                    key.pkColumns.add("id".equalsIgnoreCase(referenced)
                            && STRING_ID_TABLES.contains(key.referencedTable.toLowerCase())
                            ? "business_id" : referenced);
                }
            }
            result.addAll(byName.values());
        }
        return result;
    }

    private String metadataTable(Connection connection, String table) throws Exception {
        return table;
    }

    private String rowsValue(ResultSet rows, String column) {
        try {
            return rows.getString(column).toLowerCase();
        } catch (Exception ex) {
            throw new IllegalStateException("Could not read foreign key metadata.", ex);
        }
    }

    private List<String> allTables() {
        List<String> result = new ArrayList<>();
        result.addAll(STRING_ID_TABLES);
        result.addAll(TECHNICAL_ID_TABLES);
        result.addAll(ASSOCIATION_TABLES);
        return result;
    }

    private String abbreviate(String table) {
        return table.length() <= 35 ? table : table.substring(0, 35);
    }

    private static String identifier(String value, boolean mysql) {
        return mysql ? value : "\"" + value.replace("\"", "\"\"") + "\"";
    }

    private static final class ForeignKey {
        private final String name;
        private final String table;
        private final String referencedTable;
        private final List<String> fkColumns = new ArrayList<>();
        private final List<String> pkColumns = new ArrayList<>();

        private ForeignKey(String name, String table, String referencedTable) {
            this.name = name;
            this.table = table;
            this.referencedTable = referencedTable;
        }

        private String createSql() {
            return "ALTER TABLE " + table + " ADD CONSTRAINT " + name
                    + " FOREIGN KEY (" + String.join(", ", fkColumns) + ") REFERENCES "
                    + referencedTable + " (" + String.join(", ", pkColumns) + ")";
        }
    }
}
