CREATE TABLE IF NOT EXISTS schema_version_marker (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    marker VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
